alias gst='git statue'
alias glg='git log'
alias gco='git checkout'
alias gbc='git branch'
alias gba='git branch -av'
alias gad='git add'
alias gcm='git commit'
alias gcma='git commit --amend'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gps='git push origin'

alias cl='clear'
alias cdd='cd ~/data_struct'
